### ISSUE TITLE
Search map by street name

### ISSUE THREAD

**Issue by terryf82** [Data4Democracy/crash-model#102]
The current map setup allows risk scores to be retrieved for individual segments, but you need to know where on the map the street is you're interested in.

We need a feature that allows a street name to be typed in, and the map can shift to that specific segment to return the risk score, as well as other available data.

**Comment by alicefeng** [comment]
Hm... how is this going to be implemented given that a street does not equal a segment?  (i.e., a street is usually comprised of multiple segments) Are we returning an average?  Requiring the user to specify an individual block on the street?

I also wonder if our target audience shouldn't already be familiar with where streets are located in their cities.

**Comment by j-t-t** [comment]
If we just require them to enter an address, either a street address or an intersection by cross streets, we can geocode that address and snap it to the nearest segment.

**Comment by alicefeng** [comment]
Ok, that makes sense.

**Comment by andhint** [comment]
Would it be possible to bring in the street name when creating segments and store as an attribute of that segment like we would with speed limit?

**Comment by andhint** [comment]
Would it be possible to bring in the street name when creating segments and store as an attribute of that segment like we would with speed limit?

**Comment by j-t-t** [comment]
Street names are already part of the non-intersection segments gis file, and part of inters_data.json

**Comment by terryf82** [comment]
Interface-wise I imagine we're after some sort of basic form with an input field 'enter name of street here' which can then populate a list of segments that have a name property matching the search term. Clicking on an individual segment then centers the map on it and displays its relevant data somewhere on the screen. Are others imagining this differently?

The user then clicks on the match they're interested in, and the map re-centers with that

**Comment by alicefeng** [comment]
I think a simpler solution would be to implement something a la google maps: have a form where a user enters a street address then recenter the map to that address (and zoom in, as appropriate). The user should then be able to see the predictions for the segments near that point since those will already be displayed on the map.  

I guess one tricky thing would be since we don't output predictions for every segment, the user could potentially search for a location that's not near any of our predicted segments and therefore wouldn't see anything.  We might have to explain what it means if a segment doesn't have a prediction.
