### ISSUE TITLE
Show a city's riskiest locations

### ISSUE THREAD

**Issue by terryf82** [Data4Democracy/crash-model#123]

**Comment by terryf82** [comment]
@alicefeng do you have the data you need to be able to extract and display the riskiest segments for a city? Or does @bpben still need to clarify the location.

Similar to other viz issues perhaps we should work on a basic mockup of what this part of the interface would look like, prior to implementing?

**Comment by j-t-t** [comment]
I think we should provide a list in text format (e.g. Cambridge St between Fayette and Line, or something like that). If we want to also visualize it in some way, I'm not opposed, but I just can't think of how, and I think that the text would be easily digestible.

**Comment by alicefeng** [comment]
Yeah I think simply displaying an ordered list on the viz would be a quick and dirty way to get this done. If we want to fancy it up, we can enable the user to click on a segment in the list and zoom and recenter the map on that segment (sort of similar to #102 ).  

However, there are some data requirements to accomplish this which may fall under data generation rather than model output: I am going to need human-friendly street names for every segment since showing 100293 isn't helpful.  If we do want to do the clicking and zooming, I'll also need lat/longs for the centerpoint of each segment.

**Comment by alicefeng** [comment]
@terryf82 yes to mockups!!  But I was thinking of mocking up a design for viz 2.0 which has been slowly brewing in the back of my mind.
