### ISSUE TITLE
Create Data Dictionary

### ISSUE THREAD

**Issue by terryf82** [Data4Democracy/crash-model#157]

**Comment by terryf82** [comment]
@alicefeng could you add a short description explaining the scope of this task as I'm not sure I fully understand the application of it.

@shreyapandit is this something you have started on already? If so feel free to add any relevant details, thanks.

**Comment by alicefeng** [comment]
Thanks for creating the issue @terryf82 ! 

So what I'm looking for here is an explanation of the features in the model and the possible values they can have (which is especially important for categorical variables since those encodings may not be clear).  Specifically what I'm looking for is a table with the following:

- feature name
- description of feature (i.e., what is it)
- example values 

(The reason I'm asking for this is 1- I'd like to have an understanding of what our model is taking into consideration when generating its predictions and 2- I need to know how to translate these feature names into something more human-friendly for the interpretability part of the viz)

**Comment by shreyapandit** [comment]
Document started: https://docs.google.com/document/d/1PwA07OfSD5ELy0pPTb4ieDDKO2syrBojA_J_JRLkhk4/edit

Currently running model locally to make sure I cover everything

**Comment by shreyapandit** [comment]
I think the document can serve as a temporary point of reference until we make our schemas updated :)

**Comment by terryf82** [comment]
@shreyapandit to start migrating the Google Docs content into a markdown file in the repo.

Let me know if you need a hand.

**Comment by shreyapandit** [comment]
First pass of markdown is here: https://github.com/Data4Democracy/crash-model/pull/227

Refining some of the sources for features since our model style changed recently.
