### ISSUE TITLE
Define standard: Automated Traffic Recordings

### ISSUE THREAD

**Issue by bpben** [Data4Democracy/crash-model#92]
Same as TMCs: This is a general issue and part of the "standard definition" piece

**Comment by andhint** [comment]
This one is a bit tough since there can be so many different schemas from different vendors. When I scraped the ATR's I was getting the total volume, classifications counts (# cars/motorcycles/heavy vehicles), and mean speed over a 24-hour period. I think most of the different schemas have these aggregate stats but I don't how much further we could expand on it. 

Another thing is that some studies where done over 12-hour period or a 36-hour period. I think it might be best to normalize these stats so they're all on a "per hour" basis. That we could include a wider range of ATR studies.

**Comment by j-t-t** [comment]
@bpben @andhint @terryf82 @alicefeng @shreyapandit 
I've attached a (txt, so it would upload) draft schema for traffic volumes in general. My idea is that it can store TMCs/ATRs, as well as other speed studies (Cambridge has the 85th percentile speeds).
I'm suggesting normalized 24 hour counts - for example the TMCs were only 11 or 12 hour totals but I normalized them to 24 hours based on the volume curve from the ATRs.

**Comment by j-t-t** [comment]
[traffic-schemas.txt](https://github.com/Data4Democracy/crash-model/files/2177429/traffic-schemas.txt)

**Comment by andhint** [comment]
Should we record the original time period the counts were collected over? Even if we're going to use the normalized 24 hour counts it might be useful to have that info.

**Comment by j-t-t** [comment]
Sounds good - how about a start datetime and end datetime?

**Comment by andhint** [comment]
I don't have them in front of me but I don't think they had a start/end time. I think it was just 12hr/24hr/etc. Either would be fine though depending on what they have.
